name: "eBUSd Multi"
version: "0.2.1"
slug: "ebusd_multi"
description: "Multiple ebusd instances for Brink Renovent Excellent"
arch:
  - amd64
startup: application
boot: auto
init: false

options:
  kelder_device: "ens:192.168.2.210:9999"
  bg_device: "ens:192.168.2.211:9999"
  verdieping_device: "ens:192.168.2.212:9999"
  mqtt_host: "192.168.2.229"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""

schema:
  kelder_device: str
  bg_device: str
  verdieping_device: str
  mqtt_host: str
  mqtt_port: "int(1,65535)"
  mqtt_user: str
  mqtt_password: password