name: "eBUSd Multi"
version: "0.1.4"
slug: "ebusd_multi"
description: "Multiple ebusd instances for Brink Renovent Excellent"
arch:
  - amd64
startup: application
boot: auto
init: false

options:
  bg_device: "ens:192.168.2.211:9999"

schema:
  bg_device: str
